name: Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install flake8

      - name: Lint Python with Flake8
        run: flake8 lambda/ --max-line-length=130 --extend-ignore=E302

      - name: Run Mock Cost Analysis
        run: |
          cd lambda
          MOCK_MODE=true REPORT_BUCKET=mock-bucket PROJECT_NAME=ml-cost-optimizer python main.py || true

      - name: Terraform Format Check
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive terraform/
